### ISSUE TITLE
Adding "metadata" or something similar to a PDF

### ISSUE THREAD

**Issue by orcaman** [unidoc/unidoc-examples#13]
Hi guys,

Awesome library. I was wondering if there's a function to allow adding something like metadata to a PDF file. For example, I'd like to tag/label a certain file, but not as part of the file name and in no place that is visible to the user. 

Does this exist in PDF? Or is it something that must be implemented in the filesystem level? 

Thanks

**Comment by gunnsth** [comment]
Thanks.

Sure, PDFs can contain metadata.  Actually in the PDF reference there is a section to its specification.  Either as XML (metadata streams) or document information dictionary.

UniDoc does not have support for XML metadata streams, although I imagine it would be fairly easy to add. The document information dictionary (/Info entry under the document trailer dictionary) contains standard things such as Title, Author, .... fields.
You can add your own custom fields to this dictionary.  

Currently in UniDoc, the Info field is not exposed, but we could consider adding a hook.
For reading the field you can use the PdfReader's GetTrailer function to get the trailer dictionary, whose Info field you can then access readily.

What kind of information are you looking to add?

**Comment by orcaman** [comment]
Thanks for your reply. What I'm looking to do is to hide a piece of information, say a token, that in case the document leaks, I will know who leaked it (I am going to embed this hidden token per user who gets the document). 

If I simply insert a string into the content steam, would that work? 

For example, if I go:
```go
page.AddContentStreamByString("my secret")
```

I find that this string isn't viewable anywhere using a standard PDF reader on one hand, and it's extractable with this library on the other hand (which is what I need basically).

**Comment by gunnsth** [comment]
You certainly can do that.  However, in this specific example adding "my secret" to the content stream would be breaking the PDF standard.  Some PDF viewers may yield an error message as those are not valid PDF operands.

You could make valid PDF with "my secret" as the text.  For example placing the "my secret" as hidden text on each page (text render mode invisible).

I think the easiest way would probably be to add to the /Info entry in the document trailer.  Easy to add, easy to read back.  The disadvantage though, is that if the user would pass the PDF through another program, the information would very possibly be removed, whereas it is less likely that the PDF content stream would be processed to remove hidden texts.
