### ISSUE TITLE
example of text search and replace

### ISSUE THREAD

**Issue by gedw99** [unidoc/unidoc-examples#14]
Cant see how to do this with the current text examples.

My use case is i have a PDF that is a CAD output with text in it.
Its in English and i want to replace the text for German text.
Obviously the English to Germany text is using google translate API.

I can see how to loop the ContentStream from the examples:

````

fmt.Printf("--------------------\n")
	fmt.Printf("PDF to text extraction:\n")
	fmt.Printf("--------------------\n")
	for i := 0; i < numPages; i++ {
		pageNum := i + 1

		page, err := pdfReader.GetPage(pageNum)
		if err != nil {
			return err
		}

		contentStreams, err := page.GetContentStreams()
		if err != nil {
			return err
		}

		// If the value is an array, the effect shall be as if all of the streams in the array were concatenated,
		// in order, to form a single stream.
		pageContentStr := ""
		for _, cstream := range contentStreams {
			pageContentStr += cstream
		}

		fmt.Printf("Page %d - content streams %d:\n", pageNum, len(contentStreams))
		cstreamParser := pdfcontent.NewContentStreamParser(pageContentStr)
		txt, err := cstreamParser.ExtractText()

		if err != nil {
			return err
		}
		fmt.Printf("\"%s\"\n", txt)
	}

````

But the insert text is actually not able to replace existing text:
https://github.com/unidoc/unidoc-examples/blob/master/pdf/text/pdf_insert_text.go

Please help...

**Comment by gunnsth** [comment]
Search and replace example now available:
https://github.com/unidoc/unidoc-examples/blob/v3/pdf/text/pdf_search_replace.go
