### ISSUE TITLE
example to flatten form-filled pdf to remove fillable fields?

### ISSUE THREAD

**Issue by ttaranov** [unidoc/unidoc-examples#15]
HI there - 

nice library! is there an example that shows how to flatten a form filled pdf? 

I think I figured out how to fill forms (using acroForm.Fields and the field.V=...), although when the pdf is saved, it's saved with fillable fields (with my values). It would be best to somehow save form filled pdf into a file without any form fields present, with just values (flatten the final pdf in other words).

Thanks!

**Comment by gunnsth** [comment]
@ttaranov Not currently.  To flatten the forms, for each field you need to have an appearance stream available (or generate one if not available).  Remove the field, but display the appearance stream e.g. by adding to the content stream, for example via Do operand to display an XObject Form object.

It is a desirable feature, but not something we are working on currently.  Once we add improved support for filling and working with forms, I imagine we would like to add this capability for sure.

**Comment by ttaranov** [comment]
@gunnsth thank you for the reply. I'm wondering whether there is an easy 80% type solution to this -if flattening is limited to basic text input fields (to have these text input somehow be converted to text labels at the same positions). Do you think there is an easy way to do this without appearance stream or any new features in unidoc?

**Comment by gunnsth** [comment]
Form flattening example now available:
https://github.com/unidoc/unidoc-examples/blob/v3/pdf/forms/pdf_form_flatten.go
and more examples related to filling, fdf merging etc:
https://github.com/unidoc/unidoc-examples/tree/v3/pdf/forms
