### ISSUE TITLE
Large output sizes from split PDF

### ISSUE THREAD

**Issue by jayminkapish** [unidoc/unidoc-examples#16]
I am currently testing this with 5 pages PDF. I am doing a very simple task in golang:

First, I am splitting each page into its own pdf. Second, I take each split page PDF and merge them all into another PDF.

When I compare file size of the original PDF (200 KB) with the output of merged PDF (500 KB), merged PDF is a bigger size.

Is there a way to reduce the size of the merged PDF?

**Comment by gunnsth** [comment]
@jayminkapish Sorry that this issue went unnoticed. Any chance you can provide the original PDF for testing?  We do have optimization options (in v3 branch).  It depends on the specifics what causes the file to become larger.  Typically outputs get smaller (as unidoc tends to strip out unused information), but in some cases I can envision it could get bigger, although our optimization options could help there.

**Comment by gunnsth** [comment]
Closing as we don't have a way to reproduce this.
