### ISSUE TITLE
Missing basic examples

### ISSUE THREAD

**Issue by raliste** [unidoc/unidoc-examples#3]
Such as:

- Writing text
- Barcodes
- Basic drawing
  - Rects
  - Circles
- Transformations
  - Rotate

**Comment by gunnsth** [comment]
Hi,
Did you check out our v2 branch?  We have more examples there:
https://github.com/unidoc/unidoc-examples/tree/v2/pdf

Including some basic drawing (Rect and Circles on the way shortly) and transformations.

There is also a basic text insertion example, but somewhat limited as we are not including proper character encoding techniques yet.  Something we will add soon.

Unidoc v2 is to be released by the end of the month at which time the v2 branch for the examples will be served on the master.

Regards,
Gus

**Comment by gunnsth** [comment]
Already merged examples into master.  I think we have basic examples now, so I will close it.  Please raise issues for new specific examples :).
