### ISSUE TITLE
Example of digital sign?

### ISSUE THREAD

**Issue by sayhei** [unidoc/unidoc-examples#33]
can have any digital sign example?

**Comment by gunnsth** [comment]
Currently not here, but can see in testcases:
https://github.com/unidoc/unidoc/blob/82a1d328f85474df773a8a43ecd1390e1e3fa414/pdf/model/appender_test.go#L743

We will add more examples here later once v3.0.0 is released.

**Comment by sayhei** [comment]
yeah ,i see it ,but i only show sign with .p12 file ,can have any example of x509.Certificate? thanks

**Comment by gunnsth** [comment]
Please see examples in:
https://github.com/unidoc/unidoc-examples/tree/v3/pdf/signatures
specifically
https://github.com/unidoc/unidoc-examples/blob/v3/pdf/signatures/pdf_sign_appearance.go
which generates a pair for use with signing
