### ISSUE TITLE
example of digital sign on an pdf that already sign with another cert

### ISSUE THREAD

**Issue by sayhei** [unidoc/unidoc-examples#40]
I want to sign again on an already completed digital signature pdf. The two signed certificates are from the same parent certificate. can have any example?

**Comment by gunnsth** [comment]
I believe you should be able to sign the file again with the current examples.  The signatures are written in append mode, e.g. the changes are appended to the end of the previous file (keeping hashes in tact).  The signing process should be independent of whether previous signatures are from same parent certificate.

**Comment by sayhei** [comment]
ok,thanks
